# EDA

## Первый df1

В датасете 20к строк с признаками игр, которые собраны парсингом с сайта: https://store.steampowered.com/search?term=

- name - название игры
- description - описание
- price - цена
- reviews - оценка словесная (Very Positive, Mostly Positive и другие)
- total_reviews - всего отзывов
- total_positive - сколько положительных отзывов
- total_negative - сколько отрицательных
- system_requirements - системные требования
- tags - теги
- url - ссылка

In [1]:
import pandas as pd

df1 = pd.read_csv("steam_games_20к.xls")
print(df1.shape)
df1.head()

(20000, 10)

,name,description,price,reviews,total_reviews,total_positive,total_negative,system_requirements,tags,url
0,Counter-Strike 2,"For over two decades, Counter-Strike has offer...",Free To Play,Very Positive,9526620.0,8210053.0,1316567.0,Windows SteamOS + Linux Minimum: OS: Windows® ...,"FPS,Shooter,Multiplayer,Competitive,Action,Tea...",https://store.steampowered.com/app/730/Counter...
1,NaN,NaN,Free/Unknown,NaN,NaN,NaN,NaN,NaN,NaN,https://store.steampowered.com/app/3321460/Cri...
2,NaN,NaN,Free/Unknown,NaN,NaN,NaN,NaN,NaN,NaN,https://store.steampowered.com/app/230410/Warf...
3,Slay the Spire 2,The iconic roguelike deckbuilder returns. Craf...,$12.49 USD,Very Positive,108163.0,87625.0,20538.0,Windows macOS SteamOS + Linux Minimum: Require...,"Strategy,Roguelike,Card Game,Deckbuilding,Co-o...",https://store.steampowered.com/app/2868840/Sla...
4,NaN,NaN,Free/Unknown,NaN,NaN,NaN,NaN,NaN,NaN,https://store.steampowered.com/app/578080/PUBG...

Удалим Nan значения и дублиакты:

In [2]:
df1 = df1.dropna(subset=["name"])
df1 = df1.drop_duplicates(subset=["name"])
print(df1.shape)
df1.head()

(19038, 10)

,name,description,price,reviews,total_reviews,total_positive,total_negative,system_requirements,tags,url
0,Counter-Strike 2,"For over two decades, Counter-Strike has offer...",Free To Play,Very Positive,9526620.0,8210053.0,1316567.0,Windows SteamOS + Linux Minimum: OS: Windows® ...,"FPS,Shooter,Multiplayer,Competitive,Action,Tea...",https://store.steampowered.com/app/730/Counter...
3,Slay the Spire 2,The iconic roguelike deckbuilder returns. Craf...,$12.49 USD,Very Positive,108163.0,87625.0,20538.0,Windows macOS SteamOS + Linux Minimum: Require...,"Strategy,Roguelike,Card Game,Deckbuilding,Co-o...",https://store.steampowered.com/app/2868840/Sla...
5,Apex Legends™,"Apex Legends is the award-winning, free-to-pla...",Free To Play,Mixed,1041335.0,703602.0,337733.0,Minimum: Requires a 64-bit processor and opera...,"Free to Play,Battle Royale,Multiplayer,FPS,Sho...",https://store.steampowered.com/app/1172470/Ape...
6,ARC Raiders,ARC Raiders is a multiplayer extraction advent...,$39.99 USD,Very Positive,380901.0,327080.0,53821.0,Minimum: OS: Windows 10 or later 64-bit (lates...,"Extraction Shooter,Multiplayer,PvP,PvE,Third-P...",https://store.steampowered.com/app/1808500/ARC...
7,Gray Zone Warfare,Enter a high-stakes PvE-first open-world tacti...,$26.79 USD,Mostly Positive,69947.0,49790.0,20157.0,Minimum: Requires a 64-bit processor and opera...,"FPS,Tactical,Realistic,Extraction Shooter,Simu...",https://store.steampowered.com/app/2479810/Gra...

## Второй df2

В датасете 20к строк с признаками игр, собранных с сайта: https://rawg.io/

- id игры
- name игры
- released - дата выпуска игры
- rating игры
- ratings_count	- количество отзывов
- metacritic - агрегированный рейтинг по шкале 0–100, рассчитанный как взвешенное среднее оценок критиков с сайта Metacritic
- playtime - количество часов прохождения
- genres - жанры, например: Strategy, Simulation
- platforms	- устройства, на которых можно играть
- screenshots_count	- количество скринов на сайте про эту игру
- achievements_count - количество достижений (ачивок), которые предусмотрены для этой игры

In [3]:
df2 = pd.read_csv("rawg_games_20к.csv")
print(df2.shape)
df2.head()

(21280, 11)

,id,name,released,rating,ratings_count,metacritic,playtime,genres,platforms,screenshots_count,achievements_count
0,3498,Grand Theft Auto V,2013-09-17,4.47,7365,92.0,74,Action,"PlayStation 5, Xbox Series S/X, PlayStation 3,...",6,10.0
1,3328,The Witcher 3: Wild Hunt,2015-05-18,4.64,7180,92.0,43,"Action, RPG","PlayStation 5, Xbox Series S/X, macOS, PlaySta...",6,10.0
2,4200,Portal 2,2011-04-18,4.58,6090,95.0,11,"Shooter, Puzzle","PlayStation 3, PC, Xbox 360, Linux, macOS, Xbo...",6,10.0
3,4291,Counter-Strike: Global Offensive,2012-08-21,3.57,3635,81.0,64,Shooter,"PC, Linux, Xbox 360, PlayStation 3",6,10.0
4,5286,Tomb Raider (2013),2013-03-05,4.06,4092,86.0,10,Action,"PlayStation 3, Xbox 360, macOS, PC",6,10.0

Удалим Nan значения и дубликаты:

In [4]:
df2 = df2.dropna(subset=["name"])
df2 = df2.drop_duplicates(subset=["name"])
print(df2.shape)
df2.head()

(19960, 11)

,id,name,released,rating,ratings_count,metacritic,playtime,genres,platforms,screenshots_count,achievements_count
0,3498,Grand Theft Auto V,2013-09-17,4.47,7365,92.0,74,Action,"PlayStation 5, Xbox Series S/X, PlayStation 3,...",6,10.0
1,3328,The Witcher 3: Wild Hunt,2015-05-18,4.64,7180,92.0,43,"Action, RPG","PlayStation 5, Xbox Series S/X, macOS, PlaySta...",6,10.0
2,4200,Portal 2,2011-04-18,4.58,6090,95.0,11,"Shooter, Puzzle","PlayStation 3, PC, Xbox 360, Linux, macOS, Xbo...",6,10.0
3,4291,Counter-Strike: Global Offensive,2012-08-21,3.57,3635,81.0,64,Shooter,"PC, Linux, Xbox 360, PlayStation 3",6,10.0
4,5286,Tomb Raider (2013),2013-03-05,4.06,4092,86.0,10,Action,"PlayStation 3, Xbox 360, macOS, PC",6,10.0

## Merge по name

In [5]:
df_merged = df1.merge(df2, on='name', how='inner')
print(df_merged.shape)
df_merged.head()

(4138, 20)

,name,description,price,reviews,total_reviews,total_positive,total_negative,system_requirements,tags,url,id,released,rating,ratings_count,metacritic,playtime,genres,platforms,screenshots_count,achievements_count
0,Counter-Strike 2,"For over two decades, Counter-Strike has offer...",Free To Play,Very Positive,9526620.0,8210053.0,1316567.0,Windows SteamOS + Linux Minimum: OS: Windows® ...,"FPS,Shooter,Multiplayer,Competitive,Action,Tea...",https://store.steampowered.com/app/730/Counter...,965470,2023-09-27,3.57,210,NaN,0,Shooter,"Linux, PC",6,0.0
1,ARC Raiders,ARC Raiders is a multiplayer extraction advent...,$39.99 USD,Very Positive,380901.0,327080.0,53821.0,Minimum: OS: Windows 10 or later 64-bit (lates...,"Extraction Shooter,Multiplayer,PvP,PvE,Third-P...",https://store.steampowered.com/app/1808500/ARC...,704787,2025-10-30,3.81,44,NaN,15,Action,"PC, PlayStation 5, Xbox Series S/X",6,10.0
2,Gray Zone Warfare,Enter a high-stakes PvE-first open-world tacti...,$26.79 USD,Mostly Positive,69947.0,49790.0,20157.0,Minimum: Requires a 64-bit processor and opera...,"FPS,Tactical,Realistic,Extraction Shooter,Simu...",https://store.steampowered.com/app/2479810/Gra...,969410,2024-04-30,3.50,6,NaN,8,"Action, Shooter, Adventure, Massively Multiplayer",PC,1,NaN
3,War Thunder,War Thunder is the most comprehensive free-to-...,Free To Play,Mostly Positive,861718.0,560938.0,300780.0,Windows macOS SteamOS + Linux Minimum: OS: Win...,"Free to Play,Simulation,Vehicular Combat,Comba...",https://store.steampowered.com/app/236390/War_...,3678,2013-08-15,3.19,1040,81.0,6,"Action, Shooter, Massively Multiplayer","Xbox One, PC, macOS, Linux, PlayStation 4",6,10.0
4,Euro Truck Simulator 2,"Travel across Europe as king of the road, a tr...",$125.60 USD,Overwhelmingly Positive,944568.0,919199.0,25369.0,Windows macOS SteamOS + Linux Minimum: OS: Win...,"Driving,Transportation,Simulation,Open World,A...",https://store.steampowered.com/app/227300/Euro...,9609,2012-10-19,4.12,912,79.0,12,"Simulation, Indie","Linux, macOS, PC",6,10.0

# Обработка признаков

In [104]:
df = df_merged.copy()
df.isna().sum()

name                      0
description              11
price                     0
reviews                2151
total_reviews             1
total_positive            1
total_negative            1
system_requirements       1
tags                      0
url                       0
id                        0
released                119
rating                    0
ratings_count             0
metacritic             2808
playtime                  0
genres                   15
platforms                 0
screenshots_count         0
achievements_count     1064
dtype: int64

In [105]:
df.value_counts(["reviews"])

reviews
Very Positive              1205
Overwhelmingly Positive     429
Mostly Positive             227
Mixed                       125
Mostly Negative               1
Name: count, dtype: int64

Топ оценок

1. Overwhelmingly Positive (примерно 97 % положительно)
2. Very Positive (примерно 86 % положительно)
3. Mostly Positive (примерно 71 % положительно)
4. Mixed (примерно 67 % положительно)
5. Mostly Negative (примерно 29 % положительно)

In [106]:
rating_map = {
    "Mostly Negative": 1,
    "Mixed": 2,
    "Mostly Positive": 3,
    "Very Positive": 4,
    "Overwhelmingly Positive": 5}

df["reviews_score"] = df["reviews"].map(rating_map)
df.head()

,name,description,price,reviews,total_reviews,total_positive,total_negative,system_requirements,tags,url,...,released,rating,ratings_count,metacritic,playtime,genres,platforms,screenshots_count,achievements_count,reviews_score
0,Counter-Strike 2,"For over two decades, Counter-Strike has offer...",Free To Play,Very Positive,9526620.0,8210053.0,1316567.0,Windows SteamOS + Linux Minimum: OS: Windows® ...,"FPS,Shooter,Multiplayer,Competitive,Action,Tea...",https://store.steampowered.com/app/730/Counter...,...,2023-09-27,3.57,210,NaN,0,Shooter,"Linux, PC",6,0.0,4.0
1,ARC Raiders,ARC Raiders is a multiplayer extraction advent...,$39.99 USD,Very Positive,380901.0,327080.0,53821.0,Minimum: OS: Windows 10 or later 64-bit (lates...,"Extraction Shooter,Multiplayer,PvP,PvE,Third-P...",https://store.steampowered.com/app/1808500/ARC...,...,2025-10-30,3.81,44,NaN,15,Action,"PC, PlayStation 5, Xbox Series S/X",6,10.0,4.0
2,Gray Zone Warfare,Enter a high-stakes PvE-first open-world tacti...,$26.79 USD,Mostly Positive,69947.0,49790.0,20157.0,Minimum: Requires a 64-bit processor and opera...,"FPS,Tactical,Realistic,Extraction Shooter,Simu...",https://store.steampowered.com/app/2479810/Gra...,...,2024-04-30,3.50,6,NaN,8,"Action, Shooter, Adventure, Massively Multiplayer",PC,1,NaN,3.0
3,War Thunder,War Thunder is the most comprehensive free-to-...,Free To Play,Mostly Positive,861718.0,560938.0,300780.0,Windows macOS SteamOS + Linux Minimum: OS: Win...,"Free to Play,Simulation,Vehicular Combat,Comba...",https://store.steampowered.com/app/236390/War_...,...,2013-08-15,3.19,1040,81.0,6,"Action, Shooter, Massively Multiplayer","Xbox One, PC, macOS, Linux, PlayStation 4",6,10.0,3.0
4,Euro Truck Simulator 2,"Travel across Europe as king of the road, a tr...",$125.60 USD,Overwhelmingly Positive,944568.0,919199.0,25369.0,Windows macOS SteamOS + Linux Minimum: OS: Win...,"Driving,Transportation,Simulation,Open World,A...",https://store.steampowered.com/app/227300/Euro...,...,2012-10-19,4.12,912,79.0,12,"Simulation, Indie","Linux, macOS, PC",6,10.0,5.0

In [107]:
df = df.drop(columns=["reviews"]) # дублирует инфу из нового признака reviews_score
df = df.drop(columns=["url"]) # не показательный
df = df.drop(columns=['id']) # не показательный
df.head()

,name,description,price,total_reviews,total_positive,total_negative,system_requirements,tags,released,rating,ratings_count,metacritic,playtime,genres,platforms,screenshots_count,achievements_count,reviews_score
0,Counter-Strike 2,"For over two decades, Counter-Strike has offer...",Free To Play,9526620.0,8210053.0,1316567.0,Windows SteamOS + Linux Minimum: OS: Windows® ...,"FPS,Shooter,Multiplayer,Competitive,Action,Tea...",2023-09-27,3.57,210,NaN,0,Shooter,"Linux, PC",6,0.0,4.0
1,ARC Raiders,ARC Raiders is a multiplayer extraction advent...,$39.99 USD,380901.0,327080.0,53821.0,Minimum: OS: Windows 10 or later 64-bit (lates...,"Extraction Shooter,Multiplayer,PvP,PvE,Third-P...",2025-10-30,3.81,44,NaN,15,Action,"PC, PlayStation 5, Xbox Series S/X",6,10.0,4.0
2,Gray Zone Warfare,Enter a high-stakes PvE-first open-world tacti...,$26.79 USD,69947.0,49790.0,20157.0,Minimum: Requires a 64-bit processor and opera...,"FPS,Tactical,Realistic,Extraction Shooter,Simu...",2024-04-30,3.50,6,NaN,8,"Action, Shooter, Adventure, Massively Multiplayer",PC,1,NaN,3.0
3,War Thunder,War Thunder is the most comprehensive free-to-...,Free To Play,861718.0,560938.0,300780.0,Windows macOS SteamOS + Linux Minimum: OS: Win...,"Free to Play,Simulation,Vehicular Combat,Comba...",2013-08-15,3.19,1040,81.0,6,"Action, Shooter, Massively Multiplayer","Xbox One, PC, macOS, Linux, PlayStation 4",6,10.0,3.0
4,Euro Truck Simulator 2,"Travel across Europe as king of the road, a tr...",$125.60 USD,944568.0,919199.0,25369.0,Windows macOS SteamOS + Linux Minimum: OS: Win...,"Driving,Transportation,Simulation,Open World,A...",2012-10-19,4.12,912,79.0,12,"Simulation, Indie","Linux, macOS, PC",6,10.0,5.0

Обработка цены, оставляем просто число:

In [108]:
df["price"] = df["price"].str.lower()
df.value_counts("price")

price
$10.49 usd                 407
$8.49 usd                  342
free to play               316
$6.29 usd                  289
$12.49 usd                 164
                          ...
ato demo                     1
greyhat - prologue           1
a case of distrust demo      1
try virtuaverse now!         1
dex demo                     1
Name: count, Length: 414, dtype: int64

In [109]:
price = df["price"].str.strip()

price = price.str.replace("usd", "", regex=False)
price = price.str.replace("$", "", regex=False)
price = price.str.strip()

df["price_usd"] = pd.to_numeric(price, errors="coerce")
df["price_usd"] = df["price_usd"].fillna(0)

df = df.drop(columns=["price"])
df.head()

,name,description,total_reviews,total_positive,total_negative,system_requirements,tags,released,rating,ratings_count,metacritic,playtime,genres,platforms,screenshots_count,achievements_count,reviews_score,price_usd
0,Counter-Strike 2,"For over two decades, Counter-Strike has offer...",9526620.0,8210053.0,1316567.0,Windows SteamOS + Linux Minimum: OS: Windows® ...,"FPS,Shooter,Multiplayer,Competitive,Action,Tea...",2023-09-27,3.57,210,NaN,0,Shooter,"Linux, PC",6,0.0,4.0,0.00
1,ARC Raiders,ARC Raiders is a multiplayer extraction advent...,380901.0,327080.0,53821.0,Minimum: OS: Windows 10 or later 64-bit (lates...,"Extraction Shooter,Multiplayer,PvP,PvE,Third-P...",2025-10-30,3.81,44,NaN,15,Action,"PC, PlayStation 5, Xbox Series S/X",6,10.0,4.0,39.99
2,Gray Zone Warfare,Enter a high-stakes PvE-first open-world tacti...,69947.0,49790.0,20157.0,Minimum: Requires a 64-bit processor and opera...,"FPS,Tactical,Realistic,Extraction Shooter,Simu...",2024-04-30,3.50,6,NaN,8,"Action, Shooter, Adventure, Massively Multiplayer",PC,1,NaN,3.0,26.79
3,War Thunder,War Thunder is the most comprehensive free-to-...,861718.0,560938.0,300780.0,Windows macOS SteamOS + Linux Minimum: OS: Win...,"Free to Play,Simulation,Vehicular Combat,Comba...",2013-08-15,3.19,1040,81.0,6,"Action, Shooter, Massively Multiplayer","Xbox One, PC, macOS, Linux, PlayStation 4",6,10.0,3.0,0.00
4,Euro Truck Simulator 2,"Travel across Europe as king of the road, a tr...",944568.0,919199.0,25369.0,Windows macOS SteamOS + Linux Minimum: OS: Win...,"Driving,Transportation,Simulation,Open World,A...",2012-10-19,4.12,912,79.0,12,"Simulation, Indie","Linux, macOS, PC",6,10.0,5.0,125.60

- Удалим количество негативных и позитивных признаков, чтобы не было не нужных зависимостей с общим количеством
- Оставим только процент позитивных

In [110]:
df["positive_ratio"] = df["total_positive"] / df["total_reviews"] * 100
df = df.drop(columns=["total_positive", "total_negative"])

df.head()

,name,description,total_reviews,system_requirements,tags,released,rating,ratings_count,metacritic,playtime,genres,platforms,screenshots_count,achievements_count,reviews_score,price_usd,positive_ratio
0,Counter-Strike 2,"For over two decades, Counter-Strike has offer...",9526620.0,Windows SteamOS + Linux Minimum: OS: Windows® ...,"FPS,Shooter,Multiplayer,Competitive,Action,Tea...",2023-09-27,3.57,210,NaN,0,Shooter,"Linux, PC",6,0.0,4.0,0.00,86.180125
1,ARC Raiders,ARC Raiders is a multiplayer extraction advent...,380901.0,Minimum: OS: Windows 10 or later 64-bit (lates...,"Extraction Shooter,Multiplayer,PvP,PvE,Third-P...",2025-10-30,3.81,44,NaN,15,Action,"PC, PlayStation 5, Xbox Series S/X",6,10.0,4.0,39.99,85.870082
2,Gray Zone Warfare,Enter a high-stakes PvE-first open-world tacti...,69947.0,Minimum: Requires a 64-bit processor and opera...,"FPS,Tactical,Realistic,Extraction Shooter,Simu...",2024-04-30,3.50,6,NaN,8,"Action, Shooter, Adventure, Massively Multiplayer",PC,1,NaN,3.0,26.79,71.182467
3,War Thunder,War Thunder is the most comprehensive free-to-...,861718.0,Windows macOS SteamOS + Linux Minimum: OS: Win...,"Free to Play,Simulation,Vehicular Combat,Comba...",2013-08-15,3.19,1040,81.0,6,"Action, Shooter, Massively Multiplayer","Xbox One, PC, macOS, Linux, PlayStation 4",6,10.0,3.0,0.00,65.095310
4,Euro Truck Simulator 2,"Travel across Europe as king of the road, a tr...",944568.0,Windows macOS SteamOS + Linux Minimum: OS: Win...,"Driving,Transportation,Simulation,Open World,A...",2012-10-19,4.12,912,79.0,12,"Simulation, Indie","Linux, macOS, PC",6,10.0,5.0,125.60,97.314222

In [111]:
df.value_counts(["achievements_count"])

achievements_count
10.0                  2259
0.0                    586
1.0                     39
8.0                     34
6.0                     34
9.0                     32
7.0                     30
5.0                     17
4.0                     16
2.0                     15
3.0                     12
Name: count, dtype: int64

- по идее библиотеки achievements_count должен был отражать кол-во достижений, которые можно получить в игре, но видимо на деле данные лажовые
- system_requirements дублирует platforms и сложно интерпретируется, а так же разного не структурированного формата, поэтому так же удалим

In [112]:
df = df.drop(columns=["achievements_count", "system_requirements"])

Обработка признака даты релиза и создание признака год выпуска

In [113]:
df["released"] = pd.to_datetime(df["released"], errors="coerce")
df["release_year"] = df["released"].dt.year

Оставим только количество слов в строке описания description, а сам текстовый признак описания удалим

In [114]:
df['description_word_count'] = df['description'].str.split().str.len()
df = df.drop(columns=['description'])

Aналогично с tags

In [115]:
df['count_tags'] = df['tags'].apply(lambda x: len(x.split(',')) if isinstance(x, str) else 0)

## Обработка признака жанры

Далее идет обработка признака genres:

- добавляем столбец, в котором считается количество жарнов для каждой иргы
- добавляем 3 столбца со значениями первого, второго и третьего жанров в массиве в столбце "genres" для каждого элемента
- самые редко встречающиеся значения (меньше 40 от общего количества) записаны в один жанр (others)
- one-hot кодирование для этих признаков топ3 жанра по всем возможным жанрам
- изначальный столбец genres удаляем

In [116]:
df['count_genres'] = df['genres'].apply(lambda x: len(x.split(', ')) if isinstance(x, str) else 0)
df['count_genres'].describe()

count    4138.000000
mean        2.895118
std         1.263695
min         0.000000
25%         2.000000
50%         3.000000
75%         4.000000
max        10.000000
Name: count_genres, dtype: float64

In [117]:
split_genres = df['genres'].str.split(', ', expand=True)

split_genres = split_genres.apply(lambda x: x.str.strip() if isinstance(x, str) else x)

df['first_genre'] = split_genres[0].fillna('0')
df['second_genre'] = split_genres[1].fillna('0')
df['third_genre'] = split_genres[2].fillna('0')

df[['genres', 'first_genre', 'second_genre', 'third_genre']].head()

,genres,first_genre,second_genre,third_genre
0,Shooter,Shooter,0,0
1,Action,Action,0,0
2,"Action, Shooter, Adventure, Massively Multiplayer",Action,Shooter,Adventure
3,"Action, Shooter, Massively Multiplayer",Action,Shooter,Massively Multiplayer
4,"Simulation, Indie",Simulation,Indie,0

In [118]:
print(df['first_genre'].nunique(), df['second_genre'].nunique(), df['third_genre'].nunique())

19 19 18

In [119]:
first_genre_counts = df['first_genre'].value_counts()
second_genre_counts = df['second_genre'].value_counts()
third_genre_counts = df['third_genre'].value_counts()

small_first_genres = first_genre_counts[first_genre_counts < 40].index
small_second_genres = second_genre_counts[second_genre_counts < 40].index
small_third_genres = third_genre_counts[third_genre_counts < 40].index

df['first_genre'] = df['first_genre'].apply(lambda x: 'Other' if x in small_first_genres else x)
df['second_genre'] = df['second_genre'].apply(lambda x: 'Other' if x in small_second_genres else x)
df['third_genre'] = df['third_genre'].apply(lambda x: 'Other' if x in small_third_genres else x)

df[['first_genre', 'second_genre', 'third_genre']].head()

  first_genre second_genre            third_genre
0       Other            0                      0
1      Action            0                      0
2      Action      Shooter              Adventure
3      Action      Shooter  Massively Multiplayer
4  Simulation        Indie                      0

In [120]:
df['first_genre'].value_counts()

first_genre
Action        1869
Adventure      976
Strategy       460
RPG            272
Simulation     231
Casual         167
Other          103
Indie           60
Name: count, dtype: int64

In [121]:
df['second_genre'].value_counts()

second_genre
Adventure     840
Indie         696
0             500
RPG           428
Casual        428
Simulation    416
Strategy      314
Shooter       162
Other         153
Arcade         74
Sports         69
Racing         58
Name: count, dtype: int64

In [122]:
df['third_genre'].value_counts()

third_genre
0                        1648
Indie                    1004
RPG                       297
Casual                    294
Strategy                  195
Simulation                192
Puzzle                    161
Other                      99
Arcade                     59
Massively Multiplayer      55
Racing                     45
Platformer                 45
Adventure                  44
Name: count, dtype: int64

In [123]:
ohe_df = pd.get_dummies(df[['first_genre', 'second_genre', 'third_genre']].stack()).groupby(level=0).max()
ohe_df = ohe_df.astype(int)
df = pd.concat([df, ohe_df], axis=1)
df.drop(columns=['0']) #это были пропуски в жанрах
df.head()

,name,total_reviews,tags,released,rating,ratings_count,metacritic,playtime,genres,platforms,...,Massively Multiplayer,Other,Platformer,Puzzle,RPG,Racing,Shooter,Simulation,Sports,Strategy
0,Counter-Strike 2,9526620.0,"FPS,Shooter,Multiplayer,Competitive,Action,Tea...",2023-09-27,3.57,210,NaN,0,Shooter,"Linux, PC",...,0,1,0,0,0,0,0,0,0,0
1,ARC Raiders,380901.0,"Extraction Shooter,Multiplayer,PvP,PvE,Third-P...",2025-10-30,3.81,44,NaN,15,Action,"PC, PlayStation 5, Xbox Series S/X",...,0,0,0,0,0,0,0,0,0,0
2,Gray Zone Warfare,69947.0,"FPS,Tactical,Realistic,Extraction Shooter,Simu...",2024-04-30,3.50,6,NaN,8,"Action, Shooter, Adventure, Massively Multiplayer",PC,...,0,0,0,0,0,0,1,0,0,0
3,War Thunder,861718.0,"Free to Play,Simulation,Vehicular Combat,Comba...",2013-08-15,3.19,1040,81.0,6,"Action, Shooter, Massively Multiplayer","Xbox One, PC, macOS, Linux, PlayStation 4",...,1,0,0,0,0,0,1,0,0,0
4,Euro Truck Simulator 2,944568.0,"Driving,Transportation,Simulation,Open World,A...",2012-10-19,4.12,912,79.0,12,"Simulation, Indie","Linux, macOS, PC",...,0,0,0,0,0,0,0,1,0,0

## Анализ признака platforms

При обработке признака platforms:
- добавили признак количества устройств, на которых поддерживается каждая игра (platform_count)
- объединили все версии PlayStation, Xbox и других платформ

In [124]:
df['platform_count'] = df['platforms'].apply(lambda x: len(x.split(',')))
df['platform_count'].describe()

count    4138.000000
mean        3.059932
std         2.014999
min         1.000000
25%         1.000000
50%         3.000000
75%         4.000000
max        13.000000
Name: platform_count, dtype: float64

In [125]:
platform_count = {}

for i in df['platforms']:
    for platform in i.split(','):
        platform = platform.strip()
        if platform in platform_count:
            platform_count[platform] += 1
        else:
            platform_count[platform] = 1

platform_count

{'Linux': 1115,
 'PC': 4130,
 'PlayStation 5': 262,
 'Xbox Series S/X': 253,
 'Xbox One': 1021,
 'macOS': 1690,
 'PlayStation 4': 1156,
 'Android': 491,
 'iOS': 749,
 'Nintendo Switch': 1054,
 'PS Vita': 157,
 'Nintendo 3DS': 31,
 'Wii U': 63,
 'Xbox 360': 119,
 'PlayStation 3': 141,
 'Web': 38,
 'PSP': 28,
 'Xbox': 23,
 'Dreamcast': 6,
 'PlayStation 2': 30,
 'Wii': 23,
 'Commodore / Amiga': 8,
 'Jaguar': 2,
 '3DO': 1,
 'SEGA Saturn': 2,
 'Classic Macintosh': 11,
 'PlayStation': 10,
 'SEGA CD': 1,
 'Nintendo DS': 17,
 'Neo Geo': 4,
 'GameCube': 7,
 'Game Boy Advance': 2,
 'Nintendo 64': 1,
 'Atari ST': 2,
 'Apple II': 2,
 'NES': 3,
 'SEGA Master System': 2,
 'Genesis': 2,
 'Game Boy Color': 1,
 'Atari Lynx': 1,
 'Atari 8-bit': 1,
 'Atari 5200': 1,
 'Atari 2600': 1}

In [126]:
platform_groups = {
    'PlayStation': ['PlayStation', 'PlayStation 5', 'PlayStation 4', 'PlayStation 3', 'PS Vita', 'PlayStation 2'],
    'Xbox': ['Xbox', 'Xbox One', 'Xbox Series S/X', 'Xbox 360'],
    'Nintendo': ['Nintendo Switch', 'Nintendo DS', 'Nintendo 64', 'GameCube', 'Nintendo 3DS'],
    'SEGA': ['SEGA Saturn', 'SEGA CD', 'Genesis', 'SEGA Master System'],
    'Atari': ['Atari ST', 'Atari 8-bit', 'Atari 5200', 'Atari 2600', 'Atari Lynx'],
    'Mac': ['macOS', 'Classic Macintosh'],
    'PC': ['PC'],
    'Linux': ['Linux'],
    'Android': ['Android'],
    'iOS': ['iOS']}

In [127]:
mapping = {}
for group, platforms in platform_groups.items():
    group_count = 0
    for platform in platforms:
        group_count += platform_count.get(platform, 0)
    mapping[group] = group_count

mapping

{'PlayStation': 1756,
 'Xbox': 1416,
 'Nintendo': 1110,
 'SEGA': 7,
 'Atari': 6,
 'Mac': 1701,
 'PC': 4130,
 'Linux': 1115,
 'Android': 491,
 'iOS': 749}

In [128]:
#удалим наименее популярные платформы
del platform_groups['SEGA']
del platform_groups['Atari']

In [129]:
for platform_group, platforms in platform_groups.items():
    df[platform_group] = df['platforms'].apply(lambda x: 1 if any(platform in x.split(',') for platform in platforms) else 0)

df = df.drop(columns=['platforms'])
df.head()

,name,total_reviews,tags,released,rating,ratings_count,metacritic,playtime,genres,screenshots_count,...,Strategy,platform_count,PlayStation,Xbox,Nintendo,Mac,PC,Linux,Android,iOS
0,Counter-Strike 2,9526620.0,"FPS,Shooter,Multiplayer,Competitive,Action,Tea...",2023-09-27,3.57,210,NaN,0,Shooter,6,...,0,2,0,0,0,0,0,1,0,0
1,ARC Raiders,380901.0,"Extraction Shooter,Multiplayer,PvP,PvE,Third-P...",2025-10-30,3.81,44,NaN,15,Action,6,...,0,3,0,0,0,0,1,0,0,0
2,Gray Zone Warfare,69947.0,"FPS,Tactical,Realistic,Extraction Shooter,Simu...",2024-04-30,3.50,6,NaN,8,"Action, Shooter, Adventure, Massively Multiplayer",1,...,0,1,0,0,0,0,1,0,0,0
3,War Thunder,861718.0,"Free to Play,Simulation,Vehicular Combat,Comba...",2013-08-15,3.19,1040,81.0,6,"Action, Shooter, Massively Multiplayer",6,...,0,5,0,1,0,0,0,0,0,0
4,Euro Truck Simulator 2,944568.0,"Driving,Transportation,Simulation,Open World,A...",2012-10-19,4.12,912,79.0,12,"Simulation, Indie",6,...,0,3,0,0,0,0,0,1,0,0

In [130]:
def count_platform_types(row):
    types = 0

    if row['PlayStation'] or row['Xbox'] or row['Nintendo']:
        types += 1  # Консоли

    if row['Mac'] or row['PC'] or row['Linux']:
        types += 1  # Компьютеры

    if row['Android'] or row['iOS']:
        types += 1  # Телефоны
    return types

df['cross_platform'] = df.apply(count_platform_types, axis=1)
df

,name,total_reviews,tags,released,rating,ratings_count,metacritic,playtime,genres,screenshots_count,...,platform_count,PlayStation,Xbox,Nintendo,Mac,PC,Linux,Android,iOS,cross_platform
0,Counter-Strike 2,9526620.0,"FPS,Shooter,Multiplayer,Competitive,Action,Tea...",2023-09-27,3.57,210,NaN,0,Shooter,6,...,2,0,0,0,0,0,1,0,0,1
1,ARC Raiders,380901.0,"Extraction Shooter,Multiplayer,PvP,PvE,Third-P...",2025-10-30,3.81,44,NaN,15,Action,6,...,3,0,0,0,0,1,0,0,0,1
2,Gray Zone Warfare,69947.0,"FPS,Tactical,Realistic,Extraction Shooter,Simu...",2024-04-30,3.50,6,NaN,8,"Action, Shooter, Adventure, Massively Multiplayer",1,...,1,0,0,0,0,1,0,0,0,1
3,War Thunder,861718.0,"Free to Play,Simulation,Vehicular Combat,Comba...",2013-08-15,3.19,1040,81.0,6,"Action, Shooter, Massively Multiplayer",6,...,5,0,1,0,0,0,0,0,0,1
4,Euro Truck Simulator 2,944568.0,"Driving,Transportation,Simulation,Open World,A...",2012-10-19,4.12,912,79.0,12,"Simulation, Indie",6,...,3,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4133,Kitty Cat: Jigsaw Puzzles,315.0,"Cats,Casual,Puzzle,Cute,Psychological Horror",2016-07-18,1.78,9,NaN,4,Casual,6,...,1,0,0,0,0,1,0,0,0,1
4134,Dex,3498.0,"Cyberpunk,RPG,Female Protagonist,2D,Action,Sid...",2015-05-06,3.41,123,62.0,4,"Action, Adventure, RPG, Indie",6,...,7,1,0,0,0,0,0,0,0,1
4135,Cognition: An Erica Reed Thriller,813.0,"Point & Click,Adventure,Female Protagonist,Mys...",2013-01-30,3.68,28,NaN,4,"Adventure, Indie",6,...,2,0,0,0,1,0,0,0,0,1
4136,King Pins,106.0,"Strategy,Real Time Tactics,Action,PvP,2D,Cute,...",2020-10-24,0.00,0,NaN,1,"Action, Strategy, Indie",1,...,2,0,0,0,1,0,0,0,0,1
4137,Unhack,307.0,"Indie,Anime,Puzzle,Visual Novel,Short,Singlepl...",2015-01-09,0.00,3,NaN,3,Indie,6,...,3,0,0,0,0,0,1,0,0,1

In [132]:
(df['cross_platform'] == 0).sum()

np.int64(49)

In [133]:
print(df.shape)
df.head()

(4138, 46)

,name,total_reviews,tags,released,rating,ratings_count,metacritic,playtime,genres,screenshots_count,...,platform_count,PlayStation,Xbox,Nintendo,Mac,PC,Linux,Android,iOS,cross_platform
0,Counter-Strike 2,9526620.0,"FPS,Shooter,Multiplayer,Competitive,Action,Tea...",2023-09-27,3.57,210,NaN,0,Shooter,6,...,2,0,0,0,0,0,1,0,0,1
1,ARC Raiders,380901.0,"Extraction Shooter,Multiplayer,PvP,PvE,Third-P...",2025-10-30,3.81,44,NaN,15,Action,6,...,3,0,0,0,0,1,0,0,0,1
2,Gray Zone Warfare,69947.0,"FPS,Tactical,Realistic,Extraction Shooter,Simu...",2024-04-30,3.50,6,NaN,8,"Action, Shooter, Adventure, Massively Multiplayer",1,...,1,0,0,0,0,1,0,0,0,1
3,War Thunder,861718.0,"Free to Play,Simulation,Vehicular Combat,Comba...",2013-08-15,3.19,1040,81.0,6,"Action, Shooter, Massively Multiplayer",6,...,5,0,1,0,0,0,0,0,0,1
4,Euro Truck Simulator 2,944568.0,"Driving,Transportation,Simulation,Open World,A...",2012-10-19,4.12,912,79.0,12,"Simulation, Indie",6,...,3,0,0,0,0,0,1,0,0,1

In [134]:
df["metacritic"].isna().sum()

np.int64(2808)

In [135]:
df.to_csv('data.csv', index=False)

# Регрессия

У нас таргет metacritic (отзывы квалифицированных критиков), попробуем его предсказать для пропущенных объектов

In [ ]:
df_num = df.select_dtypes(include='number')

In [ ]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression

df_known = df_num.dropna(subset=["metacritic"])
df_unknown = df_num[df_num["metacritic"].isna()]

numeric_cols = df_num.select_dtypes(include="number").columns
feature_cols = numeric_cols.drop("metacritic")

X_train = df_known[feature_cols]
y_train = df_known["metacritic"]
X_pred = df_unknown[feature_cols]

imputer = SimpleImputer(strategy="mean")
scaler = StandardScaler()

X_train_imp = imputer.fit_transform(X_train)
X_pred_imp = imputer.transform(X_pred)

X_train_scaled = scaler.fit_transform(X_train_imp)
X_pred_scaled = scaler.transform(X_pred_imp)

linreg = LinearRegression().fit(X_train_scaled, y_train)
metacritic_pred = linreg.predict(X_pred_scaled)

df_filled = df_num.copy()
df_filled.loc[df_filled["metacritic"].isna(), "metacritic"] = metacritic_pred

coef_table = pd.DataFrame({"feature": feature_cols, "coef": linreg.coef_})

coef_table = coef_table.reindex(
    coef_table["coef"].abs().sort_values(ascending=False).index
)

print("Топ10 признаков по важности:")
print(coef_table.head(10))

Топ10 признаков по важности:
           feature      coef
7   positive_ratio  2.665381
1           rating  2.188915
2    ratings_count  1.751715
43        Strategy  1.567975
32      Simulation -1.430556
21    count_genres  1.199043
22       Adventure -1.145700
24          Casual -1.001762
41             RPG  0.869295
36          Action  0.736767

Мы понимаем, что это не релевантно, но мы оставили для дальнейшего развития проекта:)